#!/usr/bin/env python3
"""
deliverables/phase_7/scripts/test_random_monte_carlo.py
Phase 7C Task 2: Random Top-20 Monte Carlo Control (Gate 18)

Evaluates whether strategy alpha is generated by the Volar / RS ranking mechanism,
or if random selection from the filtered candidate pool produces equivalent returns.

Methodology:
  - 1,000 bootstrap simulations across 2016–2026 (128 monthly rebalances).
  - At each monthly rebalance, randomly select 20 stocks from candidates passing Filters 1, 2, 3.
  - Track equity curves, compute CAGR distribution, and calculate empirical p-value.

Pass Criteria:
  - Strategy CAGR beats median random portfolio CAGR by > 3.0 percentage points.
  - Empirical p-value < 0.05 (statistically superior at 95% confidence).

Outputs:
  - deliverables/phase_7/data_csv/gate18_random_monte_carlo.csv
  - deliverables/phase_7/raw/test_random_monte_carlo.log
"""

import sys
import os
import datetime
from pathlib import Path
from typing import Dict, List, Set, Tuple
import pandas as pd
import numpy as np

BASE_DIR = Path("/storage/emulated/0/Documents/Project MIP")
DELIV_DIR = BASE_DIR / "deliverables/phase_7"
DATA_CSV_DIR = DELIV_DIR / "data_csv"
RAW_DIR = DELIV_DIR / "raw"
DATA_DIR = BASE_DIR / "data"

if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from indian_backtest.data.bhavcopy_reader import BhavcopyReader
from indian_backtest.data.calendar_manager import CalendarManager
from indian_backtest.data.universe_manager import UniverseManager
from indian_backtest.indicators.price_extremes import is_r2_satisfied
from indian_backtest.indicators.relative_strength import calculate_relative_strength
from indian_backtest.engine.regime_filter import MarketRegimeFilter

BHAVCOPY_PATH = DATA_DIR / "adjusted_bhavcopy_max_2007_2026.parquet"
START_DATE = "2016-01-04"
END_DATE = "2026-08-31"
N_SIMULATIONS = 1000
PORTFOLIO_SIZE = 20
RNG_SEED = 42

OUT_CSV = DATA_CSV_DIR / "gate18_random_monte_carlo.csv"
OUT_LOG = RAW_DIR / "test_random_monte_carlo.log"

def main():
    DATA_CSV_DIR.mkdir(parents=True, exist_ok=True)
    RAW_DIR.mkdir(parents=True, exist_ok=True)

    log_lines = []
    def log(msg=""):
        print(msg)
        log_lines.append(msg)

    log("=" * 80)
    log("PHASE 7C TASK 2: RANDOM TOP-20 MONTE CARLO CONTROL (GATE 18)")
    log(f"Timestamp: {datetime.datetime.now(datetime.timezone.utc).isoformat()}")
    log(f"RNG Seed: {RNG_SEED} | Bootstrap Simulations: {N_SIMULATIONS}")
    log("=" * 80)

    cal_mgr = CalendarManager(base_dir=BASE_DIR, use_bhavcopy_calendar=True)
    u_mgr = UniverseManager(base_dir=BASE_DIR)
    window_days = cal_mgr.get_trading_days(START_DATE, END_DATE)
    snaps = cal_mgr.get_monthly_rebalance_snapshots(START_DATE, END_DATE)
    snap_universes = u_mgr.get_all_snapshot_universes(snaps)

    log(f"Loading Bhavcopy and benchmark data across {START_DATE} to {END_DATE}...")
    reader = BhavcopyReader(base_dir=BASE_DIR, custom_path=BHAVCOPY_PATH)
    price_lookup = reader.get_price_lookup(START_DATE, END_DATE)
    idx_df = reader.load_benchmark_index()
    benchmark_lookup = idx_df.set_index("date").to_dict(orient="index")

    b_start = benchmark_lookup[window_days[0]]["close"]
    b_end = benchmark_lookup[window_days[-1]]["close"]
    years = (pd.to_datetime(window_days[-1]) - pd.to_datetime(window_days[0])).days / 365.25
    b_cagr = (((b_end / b_start) ** (1.0 / years)) - 1.0) * 100.0

    # Baseline Strategy Actual CAGR (from Gate 5 / Gate 11 OOS)
    actual_strategy_cagr = 22.97

    log(f"Period: {window_days[0]} to {window_days[-1]} ({len(window_days)} days, {len(snaps)} snapshots)")
    log(f"Benchmark CAGR:        {b_cagr:.2f}%")
    log(f"Actual Strategy CAGR:  {actual_strategy_cagr:.2f}%")
    log("-" * 80)

    regime_filter = MarketRegimeFilter(enabled=True, ema_period=20)
    snap_day_indices = [window_days.index(s) for s in snaps]

    # Precompute candidate pools and forward returns for each monthly period
    period_candidates: List[dict] = []
    
    for s_idx, snap_date in enumerate(snaps):
        cur_day_idx = snap_day_indices[s_idx]
        is_first_day = (cur_day_idx == 0)
        u_current = snap_universes.get(snap_date, set())

        # Next trading day for execution
        exec_day_idx = cur_day_idx + 1
        if exec_day_idx >= len(window_days):
            continue
        exec_date = window_days[exec_day_idx]

        # End of holding period (next snapshot execution or final day)
        if s_idx + 1 < len(snaps):
            next_snap_idx = snap_day_indices[s_idx + 1]
            next_exec_idx = next_snap_idx + 1
            exit_date = window_days[min(next_exec_idx, len(window_days) - 1)]
        else:
            exit_date = window_days[-1]

        is_bull = regime_filter.evaluate_regime(snap_date, benchmark_lookup)

        b_ret = 0.0
        if snap_date in benchmark_lookup:
            b_ret = benchmark_lookup[snap_date].get("ret_252", 0.0)

        passing_syms = []
        forward_returns = []

        if is_bull:
            for sym in u_current:
                row = price_lookup.get((sym, snap_date))
                if row is None:
                    continue
                cl = row["close"]
                hi = row["high_252"]
                ema = row["ema_200"]
                ret_raw = row["day1_ret"] if is_first_day else row["ret_252"]

                r2_pass = is_r2_satisfied(cl, hi, 0.80)
                r3_pass = (cl >= ema) if is_first_day else (cl > ema)

                if r2_pass and r3_pass:
                    # Check entry and exit price availability
                    e_px = price_lookup.get((sym, exec_date))
                    x_px = price_lookup.get((sym, exit_date))

                    open_buy = e_px["open"] if (e_px and e_px["open"] > 0) else None
                    open_sell = x_px["open"] if (x_px and x_px["open"] > 0) else (x_px["close"] if (x_px and x_px["close"] > 0) else None)

                    if open_buy and open_sell and open_buy > 0 and open_sell > 0:
                        # 10 bps slippage + 15 bps round-trip friction
                        eff_buy = open_buy * 1.0010
                        eff_sell = open_sell * 0.9990
                        net_ret = (eff_sell / eff_buy) - 1.0
                        passing_syms.append(sym)
                        forward_returns.append(net_ret)

        period_candidates.append({
            "snap_date": snap_date,
            "exec_date": exec_date,
            "exit_date": exit_date,
            "is_bull": is_bull,
            "n_candidates": len(passing_syms),
            "returns": np.array(forward_returns, dtype=np.float64)
        })

    log(f"Precomputed candidate return pools across {len(period_candidates)} rebalance periods.")
    avg_pool_size = np.mean([p["n_candidates"] for p in period_candidates if p["is_bull"]])
    log(f"Average Bullish Filtered Pool Size: {avg_pool_size:.1f} candidate equities per rebalance.")

    # Execute 1,000 Monte Carlo bootstrap simulations
    rng = np.random.default_rng(RNG_SEED)
    random_cagrs = np.zeros(N_SIMULATIONS, dtype=np.float64)

    for sim_idx in range(N_SIMULATIONS):
        portfolio_mult = 1.0
        for p in period_candidates:
            if not p["is_bull"] or p["n_candidates"] == 0:
                continue
            rets = p["returns"]
            if len(rets) <= PORTFOLIO_SIZE:
                period_ret = np.mean(rets)
            else:
                # Randomly sample 20 stocks without replacement
                chosen_idx = rng.choice(len(rets), size=PORTFOLIO_SIZE, replace=False)
                period_ret = np.mean(rets[chosen_idx])
            portfolio_mult *= (1.0 + period_ret)

        cagr = (portfolio_mult ** (1.0 / years) - 1.0) * 100.0
        random_cagrs[sim_idx] = cagr

    median_mc = float(np.median(random_cagrs))
    mean_mc = float(np.mean(random_cagrs))
    std_mc = float(np.std(random_cagrs))
    p05_mc = float(np.percentile(random_cagrs, 5))
    p25_mc = float(np.percentile(random_cagrs, 25))
    p75_mc = float(np.percentile(random_cagrs, 75))
    p95_mc = float(np.percentile(random_cagrs, 95))
    max_mc = float(np.max(random_cagrs))
    min_mc = float(np.min(random_cagrs))

    # Empirical p-value: fraction of random runs with CAGR >= actual strategy CAGR
    beat_count = int(np.sum(random_cagrs >= actual_strategy_cagr))
    p_value = beat_count / N_SIMULATIONS
    excess_over_median = actual_strategy_cagr - median_mc

    log("\n" + "=" * 80)
    log("GATE 18 MONTE CARLO RESULTS & COMPLIANCE EVALUATION")
    log("=" * 80)
    log(f"  Actual Strategy CAGR:         {actual_strategy_cagr:.2f}%")
    log(f"  Median Random Portfolio CAGR: {median_mc:.2f}%")
    log(f"  Mean Random Portfolio CAGR:   {mean_mc:.2f}% (Std: {std_mc:.2f}%)")
    log(f"  Random CAGR Range:            {min_mc:.2f}% to {max_mc:.2f}%")
    log(f"  25th – 75th Percentile IQR:   [{p25_mc:.2f}%, {p75_mc:.2f}%]")
    log(f"  5th – 95th Percentile CI:     [{p05_mc:.2f}%, {p95_mc:.2f}%]")
    log(f"  Strategy Excess over Median:  +{excess_over_median:.2f} pp (Pass Threshold: > +3.00 pp)")
    log(f"  Random Runs Beating Strategy: {beat_count} / {N_SIMULATIONS} (Empirical p-value: {p_value:.4f})")
    log(f"  p-value Pass Threshold:       < 0.0500 (95% Confidence)")

    gate18_pass = (excess_over_median > 3.0 and p_value < 0.05)
    log(f"  Gate 18 Status:               {'PASS' if gate18_pass else 'FAIL'}")

    # Export results
    summary_record = {
        "metric": [
            "Actual Strategy CAGR (%)",
            "Benchmark CAGR (%)",
            "Median Random Portfolio CAGR (%)",
            "Mean Random Portfolio CAGR (%)",
            "Std Dev Random CAGR (%)",
            "5th Percentile Random CAGR (%)",
            "25th Percentile Random CAGR (%)",
            "75th Percentile Random CAGR (%)",
            "95th Percentile Random CAGR (%)",
            "Min Random CAGR (%)",
            "Max Random CAGR (%)",
            "Excess Return over Random Median (pp)",
            "Empirical p-value",
            "Total Monte Carlo Simulations",
            "Gate 18 Compliance Status"
        ],
        "value": [
            round(actual_strategy_cagr, 2),
            round(b_cagr, 2),
            round(median_mc, 2),
            round(mean_mc, 2),
            round(std_mc, 2),
            round(p05_mc, 2),
            round(p25_mc, 2),
            round(p75_mc, 2),
            round(p95_mc, 2),
            round(min_mc, 2),
            round(max_mc, 2),
            round(excess_over_median, 2),
            round(p_value, 4),
            N_SIMULATIONS,
            "PASS" if gate18_pass else "FAIL"
        ]
    }
    df_out = pd.DataFrame(summary_record)
    df_out.to_csv(OUT_CSV, index=False)
    log(f"\nExported Gate 18 Monte Carlo Summary: {OUT_CSV}")

    with open(OUT_LOG, "w", encoding="utf-8") as f:
        f.write("\n".join(log_lines) + "\n")

if __name__ == "__main__":
    main()
